name: bitcoin
version: 0.0.0
author: Steven Roose <stevenroose@gmail.com>
description: A Bitcoin library for Dart. Pub-test release.
homepage: http://www.dartcoin.org/
dependencies:
  asn1lib: ">=0.3.1"
  base58check: ^1.0.0
  bignum:
    git:
      url: https://github.com/nseidm1/dart-bignum.git
  bytes:
    git:
      url: https://github.com/nseidm1/dart-bytes.git
  collection: any
  cryptoutils: ">=0.1.8"
  pointycastle: any
dev_dependencies:
  environment:
    sdk: '>=1.0.0 <3.0.0'
